"use client";
import { useState } from "react";
import { Search, X } from "lucide-react";
import { PageHeader, levelLabel, levelOrder, priorityLevel } from "@/components/pulse/shared";
import { PageActions } from "@/components/pulse/page-actions";
import { deadlineOrder, getDeadline } from "@/lib/deadline";
import { ComplaintTable, EmptyResults } from "./operations-tables";
import { ComplaintDetailSheet } from "./detail-sheets";
import type { Complaint, ComplaintStatus } from "@/types/pulse";
export function Complaints({ complaints, statuses }: { complaints: Complaint[]; statuses: Record<string, ComplaintStatus> }) {
  const [query, setQuery] = useState(""); const [filters, setFilters] = useState<Record<string, string>>({}); const [selected, setSelected] = useState<Complaint | null>(null);
  const plain = (values: string[]) => [...new Set(values)].map(value => ({ value, label: value }));
  const levels = (values: string[]) => [...new Set(values)].sort((a, b) => levelOrder.indexOf(a) - levelOrder.indexOf(b)).map(value => ({ value, label: levelLabel(value) }));
  const options = { Category: plain(complaints.map(c => c.category)), Region: plain(complaints.map(c => c.region)), Priority: levels(complaints.map(c => priorityLevel(c.priority))), Status: plain(Object.values(statuses)), Deadline: deadlineOrder.filter(state => complaints.some(c => getDeadline(c)?.state === state)).map(value => ({ value, label: value })) };
  const rows = complaints.filter(c => { const values: Record<string, string> = { Category: c.category, Region: c.region, Priority: priorityLevel(c.priority), Status: statuses[c.id], Deadline: getDeadline(c)?.state ?? "" }; return Object.entries(filters).every(([key, value]) => !value || values[key] === value) && `${c.id} ${c.category} ${c.region}`.toLowerCase().includes(query.trim().toLowerCase()); });
  const active = Object.values(filters).some(Boolean) || query.trim() !== ""; const reset = () => { setFilters({}); setQuery(""); };
  const exportRows = () => [["Complaint", "Category", "Region", "Priority", "Days open", "Deadline", "Status"], ...rows.map(c => [c.id, c.category, c.region, levelLabel(priorityLevel(c.priority)), c.daysOpen, getDeadline(c)?.label ?? "", statuses[c.id] ?? ""])];
  return <><PageHeader title="Complaints" actions={<PageActions exportName="northwind-complaints" getRows={exportRows} />} /><div className="toolbar"><label className="search-box"><Search size={16} /><span className="sr-only">Search complaints</span><input placeholder="Search ID, category, region…" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="filters">{Object.entries(options).map(([label, values]) => <label key={label} className={`filter-${label.toLowerCase()}${filters[label] ? " is-active" : ""}`}><span className="filter-name" aria-hidden="true">{label}</span><span className="filter-value" aria-hidden="true">{values.find(option => option.value === filters[label])?.label ?? "All"}</span><select aria-label={label} value={filters[label] ?? ""} onChange={e => setFilters({ ...filters, [label]: e.target.value })}><option value="">All</option>{values.map(({ value, label }) => <option key={value} value={value}>{label}</option>)}</select></label>)}{active && <button type="button" className="clear-filters" onClick={reset} aria-label="Clear all filters" title="Clear all filters"><X size={13} aria-hidden="true" /><span className="clear-text">Clear</span></button>}</div><p className="table-count" role="status">{rows.length === complaints.length ? `${rows.length} complaints` : `${rows.length} of ${complaints.length} complaints`}</p></div><section className="table-section">{rows.length ? <ComplaintTable complaints={rows} statuses={statuses} selectedId={selected?.id} onSelect={setSelected} /> : <EmptyResults onReset={reset} />}</section><ComplaintDetailSheet complaint={selected} status={selected ? statuses[selected.id] : undefined} onClose={() => setSelected(null)} /></>;
}
