"use client";
import { useState } from "react";
import { DeadlineBadge, EvidenceDrawer, InfoControl, PriorityLabel, RiskBadge } from "@/components/pulse/shared";
import { Button } from "@/components/ui/button";
import { getDeadline } from "@/lib/deadline";
import { UsageChart } from "./usage-chart";
import type { AccountReviewAction, Complaint, ComplaintStatus, PreventRiskAccount, ResolutionType, UsagePoint, WorkflowComplaintStatus } from "@/types/pulse";
const n = new Intl.NumberFormat("en-CA");
export function AccountDetailSheet({ account, history, onClose }: { account: PreventRiskAccount | null; history: UsagePoint[]; onClose: () => void }) {
  return <EvidenceDrawer open={!!account} onClose={onClose} title={account?.accountId ?? "Account"} eyebrow="Account review"><>{account && <><div className="drawer-utility"><span className="muted">Billing risk</span><RiskBadge risk={account.risk} /></div><UsageChart history={history} /><dl className="facts three"><div><dt>Typical usage</dt><dd>{n.format(account.expectedUsage)} kWh</dd></div><div><dt>Estimated usage</dt><dd>{n.format(account.estimatedUsage)} kWh</dd></div><div><dt>Above typical</dt><dd>+{account.deviationPercent}%</dd></div></dl><section className="drawer-section"><h3>Why flagged</h3><ul>{account.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul></section><section className="recommendation"><h3>Recommended action</h3><p>{account.recommendedAction}</p></section><AccountReviewForm accountId={account.accountId} /></>}</></EvidenceDrawer>;
}
export function ComplaintDetailSheet({ complaint, status, onClose }: { complaint: Complaint | null; status?: ComplaintStatus; onClose: () => void }) {
  const deadline = complaint ? getDeadline(complaint) : null;
  return <EvidenceDrawer open={!!complaint} onClose={onClose} title={complaint?.id ?? "Complaint"} eyebrow="Case details">{complaint && <>
    <section className="drawer-section overview"><div className="drawer-utility"><h3>Overview</h3></div><dl className="facts"><div><dt>Category</dt><dd>{complaint.category}</dd></div><div><dt>Region</dt><dd>{complaint.region}</dd></div><div><dt>Priority</dt><dd><PriorityLabel priority={complaint.priority} /></dd></div><div><dt>Days open</dt><dd>{complaint.daysOpen}</dd></div><div><dt>Status</dt><dd><span className="status">{status ?? "Not supplied"}</span></dd></div></dl></section>
    <section className="drawer-section"><h3>Deadline</h3><dl className="facts"><div><dt className="deadline-term">Resolution deadline<InfoControl label="About resolution deadlines">Northwind sets a resolution target based on complaint priority.<br />High: 5 days · Medium: 10 days · Low: 20 days</InfoControl></dt><dd>{deadline ? <span className="deadline-detail"><strong>{deadline.label}</strong><DeadlineBadge deadline={deadline} text={deadline.state} /></span> : "No target set"}</dd></div></dl></section>
    <section className="drawer-section"><h3>Complaint details</h3><dl className="facts">{complaint.channel && <div><dt>Channel</dt><dd>{complaint.channel}</dd></div>}{complaint.sourceSystem && <div><dt>Source system</dt><dd>{complaint.sourceSystem}</dd></div>}{complaint.accountId && <div><dt>Account</dt><dd>{complaint.accountId}</dd></div>}{complaint.dateOpened && <div><dt>Opened</dt><dd>{complaint.dateOpened}</dd></div>}{complaint.dateClosed && <div><dt>Closed</dt><dd>{complaint.dateClosed}</dd></div>}{complaint.resolutionAction && <div><dt>Recorded resolution</dt><dd>{complaint.resolutionAction}</dd></div>}{complaint.billCorrectionValue !== null && complaint.billCorrectionValue !== undefined && <div><dt>Bill correction value</dt><dd>${complaint.billCorrectionValue.toFixed(2)}</dd></div>}{complaint.transferredBetweenSystems !== null && complaint.transferredBetweenSystems !== undefined && <div><dt>Transferred in source data</dt><dd>{Boolean(complaint.transferredBetweenSystems) ? "Yes" : "No"}</dd></div>}{complaint.reopened !== null && complaint.reopened !== undefined && <div><dt>Reopened in source data</dt><dd>{Boolean(complaint.reopened) ? "Yes" : "No"}</dd></div>}{complaint.slaBreach !== null && complaint.slaBreach !== undefined && <div><dt>SLA breach in source data</dt><dd>{Boolean(complaint.slaBreach) ? "Yes" : "No"}</dd></div>}</dl></section>
    <section className="drawer-section routing"><h3>Recommended handling</h3><dl className="facts"><div><dt>Recommended queue</dt><dd>{complaint.recommendedQueue}</dd></div><div><dt>Next action</dt><dd>{complaint.nextAction}</dd></div></dl></section><ComplaintWorkflowForm complaintId={complaint.id} initialStatus={status} />
  </>}</EvidenceDrawer>;
}

function AccountReviewForm({ accountId }: { accountId: string }) {
  const [action, setAction] = useState<AccountReviewAction>("Held for validation");
  const [correctedUsageKwh, setCorrectedUsageKwh] = useState("");
  const [notes, setNotes] = useState(""); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); setMessage(null); try { const response = await fetch(`/api/accounts/${encodeURIComponent(accountId)}/review`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, correctedUsageKwh: correctedUsageKwh === "" ? undefined : Number(correctedUsageKwh), notes: notes.trim() || undefined }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? "Could not save review outcome"); setMessage(body.message); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save review outcome"); } finally { setSaving(false); } }
  const needsCorrectedUsage = action === "Meter reading requested" || action === "Escalated for manual review";
  return <section className="workflow-panel"><h3>Record pre-bill decision</h3><p>Save the outcome so this review can improve future prevention rules.</p><select aria-label="Pre-bill review outcome" value={action} onChange={event => setAction(event.target.value as AccountReviewAction)}><option>Cleared for billing</option><option>Held for validation</option><option>Meter reading requested</option><option>Escalated for manual review</option></select>{needsCorrectedUsage && <label className="workflow-field"><span>Corrected customer usage <b>kWh</b></span><input aria-label="Corrected customer usage in kWh" type="number" min="0" step="1" value={correctedUsageKwh} onChange={event => setCorrectedUsageKwh(event.target.value)} placeholder="For example: 870" /></label>}<label className="workflow-field"><span>Review notes</span><textarea aria-label="Pre-bill review notes" rows={2} value={notes} onChange={event => setNotes(event.target.value)} placeholder="What did the reviewer find?" /></label><Button type="button" onClick={() => void save()} disabled={saving || (needsCorrectedUsage && correctedUsageKwh === "")}>{saving ? "Saving..." : "Save review outcome"}</Button>{message && <p className="workflow-message" role="status">{message}</p>}</section>;
}

function ComplaintWorkflowForm({ complaintId, initialStatus }: { complaintId: string; initialStatus?: ComplaintStatus }) {
  const initial: WorkflowComplaintStatus = initialStatus === "Closed" || initialStatus === "Closed - reopened" ? "Resolved" : initialStatus === "In review" ? "In progress" : "Open";
  const [status, setStatus] = useState<WorkflowComplaintStatus>(initial); const [resolutionType, setResolutionType] = useState<ResolutionType>("Bill corrected"); const [rootCause, setRootCause] = useState(""); const [notes, setNotes] = useState(""); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); setMessage(null); try { const response = await fetch(`/api/complaints/${encodeURIComponent(complaintId)}/workflow`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status, resolutionType: status === "Resolved" ? resolutionType : undefined, rootCause: rootCause.trim() || undefined, billCorrected: status === "Resolved" ? resolutionType === "Bill corrected" : undefined, notes: notes.trim() || undefined }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? "Could not save complaint update"); setMessage(body.message); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save complaint update"); } finally { setSaving(false); } }
  return <section className="workflow-panel"><h3>Update complaint</h3><p>Record progress and capture resolution feedback for future routing.</p><select aria-label="Complaint workflow status" value={status} onChange={event => setStatus(event.target.value as WorkflowComplaintStatus)}><option>Open</option><option>In progress</option><option>Resolved</option></select>{status === "Resolved" && <><select aria-label="Resolution type" value={resolutionType} onChange={event => setResolutionType(event.target.value as ResolutionType)}><option>Bill corrected</option><option>Meter reading confirmed</option><option>Information provided</option><option>Escalated</option><option>Other</option></select><input aria-label="Root cause" value={rootCause} onChange={event => setRootCause(event.target.value)} placeholder="Root cause, for example: estimated read" /></>}<textarea aria-label="Resolution notes" rows={2} value={notes} onChange={event => setNotes(event.target.value)} placeholder="What happened next?" /><Button type="button" onClick={() => void save()} disabled={saving}>{saving ? "Saving..." : status === "Resolved" ? "Save resolution" : "Save progress"}</Button>{message && <p className="workflow-message" role="status">{message}</p>}</section>;
}
