"use client";
import { DeadlineBadge, PriorityLabel, RiskBadge } from "@/components/pulse/shared";
import { getDeadline } from "@/lib/deadline";
import { Button } from "@/components/ui/button";
import type { Complaint, ComplaintStatus, PreventRiskAccount } from "@/types/pulse";
const n = new Intl.NumberFormat("en-CA");
export function AccountRiskTable({ accounts, onSelect }: { accounts: PreventRiskAccount[]; onSelect: (account: PreventRiskAccount) => void }) { return <div className="table-scroll"><table><caption className="sr-only">Pre-bill review accounts</caption><thead><tr>{["Account", "Typical usage", "Estimated usage", "Above typical", "Billing risk", "Recommended action"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{accounts.map(a => <tr key={a.accountId} className={a.risk === "HIGH" ? "high-risk-row" : undefined} onClick={() => onSelect(a)}><td><button className="record-link" onClick={e => { e.stopPropagation(); onSelect(a); }}>{a.accountId}</button></td><td>{n.format(a.expectedUsage)} kWh</td><td>{n.format(a.estimatedUsage)} kWh</td><td>+{a.deviationPercent}%</td><td><RiskBadge risk={a.risk} /></td><td>{a.recommendedAction}</td></tr>)}</tbody></table></div>; }
export function ComplaintTable({ complaints, statuses, onSelect, compact = false, selectedId }: { complaints: Complaint[]; statuses: Record<string, ComplaintStatus>; onSelect: (complaint: Complaint) => void; compact?: boolean; selectedId?: string }) { return <div className="table-scroll"><table><caption className="sr-only">Complaint records</caption><thead><tr>{["ID", "Category", "Region", "Priority", "Days open", ...(!compact ? ["Deadline"] : []), "Status"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{complaints.map(c => <tr key={c.id} className={selectedId === c.id ? "selected-row" : undefined} onClick={() => onSelect(c)}><td><button className="record-link" onClick={e => { e.stopPropagation(); onSelect(c); }}>{c.id}</button></td><td>{c.category}</td><td>{c.region}</td><td><PriorityLabel priority={c.priority} /></td><td>{c.daysOpen}</td>{!compact && <td><DeadlineCell complaint={c} /></td>}<td><span className={`status status-${(statuses[c.id] ?? "unknown").toLowerCase().replaceAll(" ", "-")}`}>{statuses[c.id] ?? "Not supplied"}</span></td></tr>)}</tbody></table></div>; }
function DeadlineCell({ complaint }: { complaint: Complaint }) { const deadline = getDeadline(complaint); return deadline ? <DeadlineBadge deadline={deadline} /> : <span className="muted">No target set</span>; }
export function EmptyResults({ onReset }: { onReset: () => void }) { return <div className="empty-results"><h3>No matching complaints</h3><Button variant="outline" onClick={onReset}>Clear filters</Button></div>; }
